version: '3.1'
services:
  app:
    build: .
    ports:
      - '3000:3000'
      - '8080:8080'
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    tty: true
  mongodb:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
volumes:
  node_modules: null
